### ISSUE TITLE
Not getting connected to API

### ISSUE THREAD

**Issue by ghost** [nandan-unni/KeyBlogs-React-Frontend#1]
https://github.com/nandan-unni/KeyBlogs-React-Frontend/blob/44891d30de4a3903cca3f5abb2643472c7d492c2/src/Pages/Blogs/ViewBlog.js#L28
On loading http://localhost:3000/blog/view/1, `username undefined` error is occurred
No calls are being received at the back-end

**Comment by Nandan-unni-zz** [comment]
Ohk, working on it.

**Comment by Nandan-unni-zz** [comment]
https://github.com/nandan-unni/KeyBlogs-React-Frontend/blob/ca77f688954ffec1f7eede47ee4f9fee34540fe7/src/Pages/Blogs/ViewBlog.js#L36

added boolean state to know whether data response from api is recieved.
